services:
  - type: web
    name: medibook
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: medibook-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: medibook-redis
          property: connectionString

  - type: redis
    name: medibook-redis
    ipAllowList: [] # Only allow internal connections
