services:
  - type: web
    name: medibook
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: medibook-redis
          property: connectionString
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: ayakakaa135@gmail.com

  - type: redis
    name: medibook-redis
    plan: free
    ipAllowList: []

databases:
  - name: medibook-db
    plan: free
